// Generated by CoffeeScript 1.9.1
(function() {
  var DecoderRing, FieldDecoder, FieldEncoder;

  FieldDecoder = require("./FieldDecoder");

  FieldEncoder = require("./FieldEncoder");

  DecoderRing = (function() {
    function DecoderRing(fieldDecoder, fieldEncoder) {
      this.fieldDecoder = fieldDecoder != null ? fieldDecoder : new FieldDecoder;
      this.fieldEncoder = fieldEncoder != null ? fieldEncoder : new FieldEncoder;
    }

    DecoderRing.prototype.decode = function(buffer, spec) {
      var decodeFun, field, i, len, obj, ref;
      obj = {};
      if (spec.bigEndian) {
        decodeFun = this.fieldDecoder.decodeFieldBE;
      } else {
        decodeFun = this.fieldDecoder.decodeFieldLE;
      }
      ref = spec.fields;
      for (i = 0, len = ref.length; i < len; i++) {
        field = ref[i];
        obj[field.name] = decodeFun(buffer, field);
      }
      return obj;
    };

    DecoderRing.prototype.encode = function(obj, spec) {
      var bitFieldAccumulator, buffer, currentVal, encodeFun, fieldSpec, i, j, len, len1, r, ref, ref1, ref2, size, val;
      size = (ref = spec.length) != null ? ref : this.fieldEncoder.findSpecBufferSize(spec);
      buffer = new Buffer(size);
      buffer.fill(0);
      if (spec.bigEndian) {
        encodeFun = this.fieldEncoder.encodeFieldBE;
      } else {
        encodeFun = this.fieldEncoder.encodeFieldLE;
      }
      bitFieldAccumulator = {};
      ref1 = spec.fields;
      for (i = 0, len = ref1.length; i < len; i++) {
        fieldSpec = ref1[i];
        if (fieldSpec.type !== 'bit') {
          buffer = encodeFun(buffer, obj, fieldSpec);
        } else {
          val = obj[fieldSpec.name] ? Math.pow(2, fieldSpec.position) : 0;
          currentVal = bitFieldAccumulator["" + fieldSpec.start] || 0;
          bitFieldAccumulator["" + fieldSpec.start] = currentVal + val;
        }
      }
      ref2 = Object.keys(bitFieldAccumulator);
      for (j = 0, len1 = ref2.length; j < len1; j++) {
        r = ref2[j];
        buffer = encodeFun(buffer, bitFieldAccumulator, {
          name: r,
          start: parseInt(r),
          type: 'uint8'
        });
      }
      return buffer;
    };

    return DecoderRing;

  })();

  module.exports = DecoderRing;

}).call(this);
